// <auto-generated />
using System;
using HalcyonApparelsInfrastructure.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalcyonApparelsInfrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230119072454_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.AccessoryDetails", b =>
                {
                    b.Property<int>("AccessoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessoryId"));

                    b.Property<string>("AccessoryBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("AccessoryDiscount")
                        .HasColumnType("DECIMAL");

                    b.Property<string>("AccessoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("AccessoryPrice")
                        .HasColumnType("DECIMAL");

                    b.Property<string>("AccessoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderDetailsId")
                        .HasColumnType("INT");

                    b.HasKey("AccessoryId");

                    b.HasIndex("OrderDetailsId");

                    b.ToTable("AccessoryDetails");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.AccessoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccsryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("AccessoryType");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.AdminLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("AdminLogin");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.CustomerDetails", b =>
                {
                    b.Property<string>("ContactId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("ContactId");

                    b.ToTable("CustomerDetails");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.CustomerMarketing", b =>
                {
                    b.Property<string>("ContactId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Product_Type__c")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("ContactId");

                    b.ToTable("CustomerMarketing");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.LoginCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("LoginCredentials");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact__c")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CustomerDetailsContactId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Parent_Order_Id__c")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Product_Type__c")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("date_of_order__c")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CustomerDetailsContactId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProdType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.AccessoryDetails", b =>
                {
                    b.HasOne("HalcyonApparelsDomain.Entities.OrderDetails", null)
                        .WithMany("accessoryTypes")
                        .HasForeignKey("OrderDetailsId");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.AccessoryType", b =>
                {
                    b.HasOne("HalcyonApparelsDomain.Entities.ProductType", null)
                        .WithMany("accessoryTypes")
                        .HasForeignKey("ProductTypeId");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.OrderDetails", b =>
                {
                    b.HasOne("HalcyonApparelsDomain.Entities.CustomerDetails", null)
                        .WithMany("orderList")
                        .HasForeignKey("CustomerDetailsContactId");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.CustomerDetails", b =>
                {
                    b.Navigation("orderList");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.OrderDetails", b =>
                {
                    b.Navigation("accessoryTypes");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.ProductType", b =>
                {
                    b.Navigation("accessoryTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
